language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - python setup.py install
  - pip install coveralls
  - pip install --install-option="--no-cython-compile" cython
  - pip install numpy
  - pip install scipy
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
script:
  - "nosetests --with-coverage --cover-package=oll"
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - yukino0131@me.com
    on_success: always
    on_failure: always
